name: Publish docs with MkDocs via GitHub Pages
on:
  push:
    branches:
      - main
      - feature/gh-page-action-setup

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[docs]"
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
